project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Crime in NY"
  author:
    - Elie Chemouni (ec3778)
    - Martin Fluder (mf3590)
  repo-url: https://github.com/fluderm/Crime_NY
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


