# Introduction


<!-- 

Explain why you chose this topic, and the questions you are interested in studying. Provide context for readers who are not familiar with the topic.

(suggested: 1 page) 

-->


While deciding on a topic for our project, we received several emails from the Columbia Department of Safety about an armed robbery near the Columbia campus. This prompted us to get interested in Crime data in and around NYC – in particular; it made us question the safety around Columbia and in NYC specifically. We found several exciting and detailed datasets about crime in NYC and quickly focused on [NYC incident-level shootings](https://data.cityofnewyork.us/Public-Safety/NYPD-Shooting-Incident-Data-Historic-/833y-fsy8) data in the past ten years to see in how much “danger” we are:

```{r, echo=FALSE,results='hide', message=FALSE, warning=FALSE}

library(ggplot2)
library(sp)
library(sf)
library(RColorBrewer)

crime_nyc <- read.csv('../data/NYPD_Shooting_Incident_Data__Historic__20231124.csv')
crime_nyc$OCCUR_DATE <- as.Date(crime_nyc$OCCUR_DATE, format = '%m/%d/%Y')

crime_nyc_nona <- crime_nyc[complete.cases(crime_nyc$Longitude, crime_nyc$Latitude), ]
crime_nyc_nona <- subset(crime_nyc_nona, select = -JURISDICTION_CODE)
crime_nyc_nona <- crime_nyc_nona[(crime_nyc_nona$OCCUR_DATE > as.Date('2015-01-01')), ]

nyc_boundaries <- st_read('data/nyc_election_districts/nyc_election_districts.shp')
crime_nyc_sf <- st_as_sf(crime_nyc_nona, coords = c("Longitude", "Latitude"), crs = 4326)

ggplot() +
  geom_sf(data = nyc_boundaries, 
          fill = "lightblue",
          color = "black") +
  geom_density_2d_filled(data = crime_nyc_nona, 
                         aes(x = Longitude, y = Latitude),
                         alpha = 0.85) +
  labs(title = "Density Plot for Number of shootings in NYC from 2015 - 2022") +
  theme_minimal()

```
(This plot is just for \"motivational\" purposes. In the main body of the text we shall focus on a different dataset.)

Indeed, it seems like there is a relative “hotspot” of shooting incidences near Columbia. The hotspot is mostly several blocks from campus, but it is insightful to us to know which areas to avoid.

This first broad analysis took us down a rabbit hole of crime and crime-related datasets. We eventually decided to focus on NY State data, as it provides a less localized, more widespread, and comprehensive view of crimes over the years. Furthermore, NY State seems more representative of drastically different styles of living, which – we believe – allows for a more contrasting picture. This topic is attractive due to its insights into crime trends over time and across different areas.

Our primary dataset encompasses detailed crime statistics for each agency in New York State's counties spanning from 1990 to 2022. This extensive temporal range of approximately three decades enables a thorough examination of the evolution of crime patterns within each New York county. Moreover, it facilitates a comparative analysis of crime statistics between New York City and the entire state.  

In our exploration, we aim to address various questions related to crime dynamics, patterns, and potential influencing factors. For example, we will delve into the examination of how socioeconomic factors, law enforcement strategies, and demographic shifts may have impacted crime rates over the years. Additionally, we are interested in investigating the influence of the COVID-19 pandemic on crime statistics, both in terms of overall rates and the types of crimes reported.  

To enhance the depth of our analysis, we have supplemented our primary dataset with additional data providing population numbers for each county in New York State for the time period covered in our crime dataset. This supplementary information is crucial as it allows us to calculate and compare crime rates adjusted for population size. By doing so, we aim to provide a more nuanced understanding of crime trends and ensure that our analysis considers variations in population density across different counties. This entails delving into the intricate interrelationships and connections between various crime categories and their associations with the counties in the state of New York. Our scrutiny extends to comparisons across different time periods, with a particular emphasis on discerning any discernible disparities that may exist between counties within New York City (NYC) and those outside the city limits. This strategic shift allows us to unveil nuanced patterns and variations in crime dynamics, providing a comprehensive understanding of how these phenomena unfold across distinct temporal and geographical contexts. 

We will also focus on the last three decades to investigate the impact of the stop-and-frisk policy implemented in the early 2000s.Our investigative approach involves a meticulous comparison of crime rates between NYC and counties outside its jurisdiction, encompassing diverse time periods. By adopting this methodological lens, we aim to paint a comprehensive picture of the policy's influence on overall crime statistics. This analytical endeavor allows us to discern trends, patterns, and shifts in criminal activities, providing valuable insights into the multifaceted impact of "Operation Impact" on the broader landscape of crime dynamics. Through this extensive exploration, we strive to contribute to a nuanced understanding of the policy's effects and implications within the broader context of crime trends in both NYC and non-NYC counties.

Ultimately, our research endeavors not only contribute to a comprehensive analysis of public safety trends but also serve as a valuable resource for policymakers and the public. The insights derived from this study can aid in developing informed strategies to understand and address various crime-related issues within the state of New York.

<!--
#https://data.ny.gov/Government-Finance/Annual-Population-Estimates-for-New-York-State-and/krt9-ym2k
-->
